# Generated by Django 4.2.5 on 2023-09-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cart'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
