# Generated by Django 4.2.4 on 2023-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages/'),
        ),
    ]
