# Generated by Django 4.2.4 on 2023-09-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='product_id',
            new_name='product',
        ),
    ]
