# Generated by Django 4.2.5 on 2023-09-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='image',
        ),
    ]
